import { makeStory } from "https://cdn.jsdelivr.net/npm/plotteus";

const group1 = [
  {
    key: "El mundo",
    data: [
      { key: "Switzerland", value: 7.587 },
      { key: "Iceland", value: 7.561 },
      { key: "Denmark", value: 7.527 },
      { key: "Norway", value: 7.522 },
      { key: "Canada", value: 7.427 },
      { key: "Finland", value: 7.406 },
      { key: "Netherlands", value: 7.378 },
      { key: "Sweden", value: 7.364 },
      { key: "New Zealand", value: 7.286 },
      { key: "Australia", value: 7.284 },
      { key: "Israel", value: 7.278 },
      { key: "Costa Rica", value: 7.226 },
      { key: "Austria", value: 7.2 },
      { key: "Mexico", value: 7.187 },
      { key: "United States", value: 7.119 },
      { key: "Brazil", value: 6.983 },
      { key: "Luxembourg", value: 6.946 },
      { key: "Ireland", value: 6.94 },
      { key: "Belgium", value: 6.937 },
      { key: "United Arab Emirates", value: 6.901 },
      { key: "United Kingdom", value: 6.867 },
      { key: "Oman", value: 6.853 },
      { key: "Venezuela", value: 6.81 },
      { key: "Singapore", value: 6.798 },
      { key: "Panama", value: 6.786 },
      { key: "Germany", value: 6.75 },
      { key: "Chile", value: 6.67 },
      { key: "Qatar", value: 6.611 },
      { key: "France", value: 6.575 },
      { key: "Argentina", value: 6.574 },
      { key: "Czech Republic", value: 6.505 },
      { key: "Uruguay", value: 6.485 },
      { key: "Colombia", value: 6.477 },
      { key: "Thailand", value: 6.455 },
      { key: "Saudi Arabia", value: 6.411 },
      { key: "Spain", value: 6.329 },
      { key: "Malta", value: 6.302 },
      { key: "Taiwan", value: 6.298 },
      { key: "Kuwait", value: 6.295 },
      { key: "Suriname", value: 6.269 },
      { key: "Trinidad and Tobago", value: 6.168 },
      { key: "El Salvador", value: 6.13 },
      { key: "Guatemala", value: 6.123 },
      { key: "Uzbekistan", value: 6.003 },
      { key: "Slovakia", value: 5.995 },
      { key: "Japan", value: 5.987 },
      { key: "South Korea", value: 5.984 },
      { key: "Ecuador", value: 5.975 },
      { key: "Bahrain", value: 5.96 },
      { key: "Italy", value: 5.948 },
      { key: "Bolivia", value: 5.89 },
      { key: "Moldova", value: 5.889 },
      { key: "Paraguay", value: 5.878 },
      { key: "Kazakhstan", value: 5.855 },
      { key: "Slovenia", value: 5.848 },
      { key: "Lithuania", value: 5.833 },
      { key: "Nicaragua", value: 5.828 },
      { key: "Peru", value: 5.824 },
      { key: "Belarus", value: 5.813 },
      { key: "Poland", value: 5.791 },
      { key: "Malaysia", value: 5.77 },
      { key: "Croatia", value: 5.759 },
      { key: "Libya", value: 5.754 },
      { key: "Russia", value: 5.716 },
      { key: "Jamaica", value: 5.709 },
      { key: "North Cyprus", value: 5.695 },
      { key: "Cyprus", value: 5.689 },
      { key: "Algeria", value: 5.605 },
      { key: "Kosovo", value: 5.589 },
      { key: "Turkmenistan", value: 5.548 },
      { key: "Mauritius", value: 5.477 },
      { key: "Hong Kong", value: 5.474 },
      { key: "Estonia", value: 5.429 },
      { key: "Indonesia", value: 5.399 },
      { key: "Vietnam", value: 5.36 },
      { key: "Turkey", value: 5.332 },
      { key: "Kyrgyzstan", value: 5.286 },
      { key: "Nigeria", value: 5.268 },
      { key: "Bhutan", value: 5.253 },
      { key: "Azerbaijan", value: 5.212 },
      { key: "Pakistan", value: 5.194 },
      { key: "Jordan", value: 5.192 },
      { key: "Montenegro", value: 5.192 },
      { key: "China", value: 5.14 },
      { key: "Zambia", value: 5.129 },
      { key: "Romania", value: 5.124 },
      { key: "Serbia", value: 5.123 },
      { key: "Portugal", value: 5.102 },
      { key: "Latvia", value: 5.098 },
      { key: "Philippines", value: 5.073 },
      { key: "Somaliland region", value: 5.057 },
      { key: "Morocco", value: 5.013 },
      { key: "Macedonia", value: 5.007 },
      { key: "Mozambique", value: 4.971 },
      { key: "Albania", value: 4.959 },
      { key: "Bosnia and Herzegovina", value: 4.949 },
      { key: "Lesotho", value: 4.898 },
      { key: "Dominican Republic", value: 4.885 },
      { key: "Laos", value: 4.876 },
      { key: "Mongolia", value: 4.874 },
      { key: "Swaziland", value: 4.867 },
      { key: "Greece", value: 4.857 },
      { key: "Lebanon", value: 4.839 },
      { key: "Hungary", value: 4.8 },
      { key: "Honduras", value: 4.788 },
      { key: "Tajikistan", value: 4.786 },
      { key: "Tunisia", value: 4.739 },
      { key: "Palestinian Territories", value: 4.715 },
      { key: "Bangladesh", value: 4.694 },
      { key: "Iran", value: 4.686 },
      { key: "Ukraine", value: 4.681 },
      { key: "Iraq", value: 4.677 },
      { key: "South Africa", value: 4.642 },
      { key: "Ghana", value: 4.633 },
      { key: "Zimbabwe", value: 4.61 },
      { key: "Liberia", value: 4.571 },
      { key: "India", value: 4.565 },
      { key: "Sudan", value: 4.55 },
      { key: "Haiti", value: 4.518 },
      { key: "Congo (Kinshasa)", value: 4.517 },
      { key: "Nepal", value: 4.514 },
      { key: "Ethiopia", value: 4.512 },
      { key: "Sierra Leone", value: 4.507 },
      { key: "Mauritania", value: 4.436 },
      { key: "Kenya", value: 4.419 },
      { key: "Djibouti", value: 4.369 },
      { key: "Armenia", value: 4.35 },
      { key: "Botswana", value: 4.332 },
      { key: "Myanmar", value: 4.307 },
      { key: "Georgia", value: 4.297 },
      { key: "Malawi", value: 4.292 },
      { key: "Sri Lanka", value: 4.271 },
      { key: "Cameroon", value: 4.252 },
      { key: "Bulgaria", value: 4.218 },
      { key: "Egypt", value: 4.194 },
      { key: "Yemen", value: 4.077 },
      { key: "Angola", value: 4.033 },
      { key: "Mali", value: 3.995 },
      { key: "Congo (Brazzaville)", value: 3.989 },
      { key: "Comoros", value: 3.956 },
      { key: "Uganda", value: 3.931 },
      { key: "Senegal", value: 3.904 },
      { key: "Gabon", value: 3.896 },
      { key: "Niger", value: 3.845 },
      { key: "Cambodia", value: 3.819 },
      { key: "Tanzania", value: 3.781 },
      { key: "Madagascar", value: 3.681 },
      { key: "Central African Republic", value: 3.678 },
      { key: "Chad", value: 3.667 },
      { key: "Guinea", value: 3.656 },
      { key: "Ivory Coast", value: 3.655 },
      { key: "Burkina Faso", value: 3.587 },
      { key: "Afghanistan", value: 3.575 },
      { key: "Rwanda", value: 3.465 },
      { key: "Benin", value: 3.34 },
      { key: "Syria", value: 3.006 },
      { key: "Burundi", value: 2.905 },
      { key: "Togo", value: 2.839 },
    ],
  },
];

const group2 = [
  {
    key: "Australia and New Zealand",
    data: [
      { key: "New Zealand", value: 7.286 },
      { key: "Australia", value: 7.284 },
    ],
  },
  {
    key: "Central and Eastern Europe",
    data: [
      { key: "Russia", value: 5.716 },
      { key: "Croatia", value: 5.759 },
      { key: "Georgia", value: 4.297 },
      { key: "Poland", value: 5.791 },
      { key: "Belarus", value: 5.813 },
      { key: "Tajikistan", value: 4.786 },
      { key: "Macedonia", value: 5.007 },
      { key: "Slovenia", value: 5.848 },
      { key: "Kazakhstan", value: 5.855 },
      { key: "Moldova", value: 5.889 },
      { key: "Czech Republic", value: 6.505 },
      { key: "Slovakia", value: 5.995 },
      { key: "Uzbekistan", value: 6.003 },
      { key: "Lithuania", value: 5.833 },
      { key: "Kosovo", value: 5.589 },
      { key: "Turkmenistan", value: 5.548 },
      { key: "Ukraine", value: 4.681 },
      { key: "Latvia", value: 5.098 },
      { key: "Bulgaria", value: 4.218 },
      { key: "Serbia", value: 5.123 },
      { key: "Romania", value: 5.124 },
      { key: "Armenia", value: 4.35 },
      { key: "Montenegro", value: 5.192 },
      { key: "Hungary", value: 4.8 },
      { key: "Azerbaijan", value: 5.212 },
      { key: "Bosnia and Herzegovina", value: 4.949 },
      { key: "Kyrgyzstan", value: 5.286 },
      { key: "Estonia", value: 5.429 },
      { key: "Albania", value: 4.959 },
    ],
  },
  {
    key: "Australia and New Zealand2",
    data: [
      { key: "New Zealand", value: 7.286 },
      { key: "Australia", value: 7.284 },
    ],
  },
  {
    key: "Australia and New Zealand2",
    data: [
      { key: "New Zealand", value: 7.286 },
      { key: "Australia", value: 7.284 },
    ],
  },
  {
    key: "Australia and New Zealand3",
    data: [
      { key: "New Zealand", value: 7.286 },
      { key: "Australia", value: 7.284 },
    ],
  },
  {
    key: "Australia and New Zealand4",
    data: [
      { key: "New Zealand", value: 7.286 },
      { key: "Australia", value: 7.284 },
    ],
  },
];
const showValues = false;
const showDatumLabels = false;
const palette = "default";
const steps = [
  {
    key: "zero",
    chartType: "bar",
    title: "Indices de felicidad",
    titleAnchor: "middle",
    subtitle: "Fuente: www.kaggle.com/datasets/unsdsn/world-happiness",
    subtitleAnchor: "middle",
    showValues,
    showDatumLabels,
    palette,
    group1,
  },
  {
    key: "one",
    chartType: "pie",
    title: "Indices de felicidad",
    titleAnchor: "middle",
    subtitle: "Fuente: www.kaggle.com/datasets/unsdsn/world-happiness",
    subtitleAnchor: "middle",
    showValues,
    showDatumLabels,
    palette,
    group1,
  },
  {
    key: "two",
    chartType: "bubble",
    title: "Indices de felicidad",
    titleAnchor: "middle",
    subtitle: "Fuente: www.kaggle.com/datasets/unsdsn/world-happiness",
    subtitleAnchor: "middle",
    showValues,
    showDatumLabels,
    palette,
    group1,
  },
  {
    key: "three",
    chartType: "bar",
    chartSubtype: "stacked",
    title: "Indices de felicidad",
    titleAnchor: "middle",
    subtitle: "Fuente: www.kaggle.com/datasets/unsdsn/world-happiness",
    subtitleAnchor: "middle",
    showValues,
    showDatumLabels,
    palette,
    group1,
  },
  {
    key: "four",
    chartType: "treemap",
    title: "Indices de felicidad",
    titleAnchor: "middle",
    subtitle: "Fuente: www.kaggle.com/datasets/unsdsn/world-happiness",
    subtitleAnchor: "middle",
    showValues,
    showDatumLabels,
    palette,
    group1,
  },
];
const story = makeStory(document.querySelector("#story"), steps);

story.render("zero", 1);
let input = document.getElementById("range_input");
input.addEventListener("input", (event) => {
  if (event.target.value < 0.5) {
    story.render("zero", event.target.value * 2);
  } else {
    story.render("one", (event.target.value - 0.5) * 2);
  }
});
